repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
      - id: debug-statements
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: ["--unsafe"] # needed for !! tags in mkdocs.yml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Ruff replaces black, flake8, autoflake, isort and more
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.11.10" # make sure this is always consistent with hatch configs
    hooks:
      - id: ruff
      - id: ruff-format
        args: [--config, ./pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0" # make sure this is always consistent with hatch configs
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive"]
        additional_dependencies: [types-tabulate, types-cachetools]
  - repo: .
    rev: v0.4.1
    hooks:
      - id: cronspell
        name: cronspell
        entry: cronspell preflight
        language: python
        types: [yaml]
        pass_filenames: true
        additional_dependencies:
          - ".[cli]"
        args: ["--yamlpath", "/*/rel_date"]
        files: .*/demo\.cfg\.ya?ml$
  - repo: local
    hooks:
      - id: version_in_readme
        name: version_in_readme
        entry: |-
          bash -c '\
            export LATEST_TAG=$(git tag  --contains $( git describe --tags $(git rev-list --tags --max-count=1) )) ;
            sed -Ei "s/(\s+)rev:.*/\1rev: "$( git rev-list -1 $LATEST_TAG  )"/" README.md && \
            sed -Ei "s/(\s+)rev: (\S+).*/\1rev: \2   \# "$LATEST_TAG"/" README.md'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: generate_docs
        name: generate_docs
        entry: |-
          bash -c 'hatch run docs:tex2md'
        language: system
        pass_filenames: false
