# SPDX-FileCopyrightText: 2024-present iilei • jochen preusche <922226+iilei@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- id: cronspell
  name: cronspell
  description: This hook uses https://iilei.github.io/cronspell/details/cli/#pre-commit to validate cronspell date expressions
  entry: cronspell preflight
  language: python
  types: [yaml]
  pass_filenames: true
  additional_dependencies:
    - ".[cli]"
  args: ["--yamlpath", "/*/cronspell"]
