name: Build

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: ['3.9']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch pre-commit
          hatch env create
      - name: Lint and typecheck
        run: |
          hatch run lint:all
      - name: Run Tests
        run: |
          hatch run test:pytest --cov-report term --cov-report xml:coverage.xml --cov=cronspell
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  release:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://test.pypi.org/p/cronspell
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install hatch pre-commit
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Inject Version @ Readme
        run: |
          cp README.md _data/
          sed -i -e 's/{{ version }}/${{ steps.get-latest-tag.outputs.tag }}/g' _data/README.md
      - name: Build
        run: |
          rm -rf ./dist
          hatch build
          ls -lisa dist
      - name: Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
