name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
